config/routes.rb
Mypolice::Application.routes.draw do |map|
  resources :addresses

  resources :responses

  devise_for :polices

  devise_for :admins

  resources :posts do
    resources :responses
    resources :comments
  end
  
  resources :tags

  namespace :admin do 
    resources :posts do  
        post :approve, :on => :member
        post :unapprove, :on => :member
        get :approved, :on => :collection
        get :unapproved, :on => :collection
      end
    resources :comments do  
        post :approve, :on => :member
        post :unapprove, :on => :member
        get :approved, :on => :collection
        get :unapproved, :on => :collection
      end
    resources :polices do
        post :cheif, :on => :member
        post :uncheif, :on =>:member
    end
    resources :responses, :users, :tags, :categories, :whos
  end

  namespace :police do
    resources :polices
  end

  devise_for :users  
  
  match "/admin" => "admin/dashboard#index", :as => :admin_root
  match "/police" => "police/dashboard#index", :as => :police_root
   
  match '/police/profile/:id/' => 'police/polices#show', :as => :profile   

  match '/about'=>'about#index', :as =>:about_root
  match '/tools'=>'tools#index', :as =>:tools_root
  match 'police/help'=>"police/help#index", :as=>:police_help_root

  match '/tellusyourstory'=>'posts#new', :as=>:tellusyourstory

  root :to =>"home#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :presence=>true
  belongs_to :post
  belongs_to :user
  scope :approved, where(:approved => true)
  scope :unapproved, where(:approved => false)
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
   before_filter :authenticate_admin!

  def index
    @comments = Comment.paginate :page=>params[:page], :per_page=>'10', :order=>'created_at DESC'
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
      format.json { render :json => @comments}
    end
  end

  def show
    @comment = Comment.find(params[:id])
    @post = Post.find(@comment.post_id)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end


  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to([:admin, @comment], :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(admin_comments_url, :notice =>'Successfully deleted ') }
      format.xml  { head :ok }
    end
  end
 
    def approve
    @comment = Comment.find(params[:id])
    @comment.update_attribute :approved, true
    flash[:notice] = "approved"
    respond_to do |format|
      format.html {redirect_to(admin_comments_url)}
    end
  end

   def unapprove
    @comment = Comment.find(params[:id])
    @comment.update_attribute :approved, false
    flash[:notice] = "unapproved"
    respond_to do |format|
      format.html {redirect_to(admin_comments_url)}
    end
  end

   def approved
    #@posts = Comment.where(:approved => true)
      @comments = Comment.approved.paginate :page=>params[:page], :per_page=>'10', :order=>'created_at DESC'

     render :action=>"index"
   end

   def unapproved
      #@comments = Comment.where(:approved => false)
      @comments = Comment.unapproved.paginate :page=>params[:page], :per_page=>'10', :order=>'created_at DESC'
      render :action=>"index"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, :only => [:create]
  def new
    @comment = Comment.new
  end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(params[:comment])
    @comment.user = current_user
    flash[:notice] = "Thanks for your comment! It will be appproved soon"
    respond_to do |format|
      if @comment.save
        format.html{ redirect_to @post, :notice =>"comment was created, but need to be approved"}
        format.js
      else 
        format.html{redirect_to @post}
      end
    end
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_comment.html.erb
<% div_for comment do %>
  <p>
  <strong> Posted by <%= (comment.user.email) %> <%= time_ago_in_words(comment.created_at) %>
    ago</strong><br />
    <%= (comment.body) %>
  </p>
<% end%>

app/views/admin/comments/_form.html.erb
<%= form_for([:admin,@comment]) do |f| %>
<%= render "shared/error_message", :target => [@comment] %>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<%=end%>

app/views/admin/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @comment] %> |
<%= link_to 'Back', admin_comments_path %> 

app/views/admin/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.post_id %></td>
    <td><%= comment.body %></td>
    <td><%= link_to 'Show', [:admin, comment] %></td>
    <td><%= link_to 'Edit', edit_admin_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', [:admin, comment], :confirm => 'Are you sure?', :method => :delete %></td>
   <% if comment.approved %>
     <td> <%= link_to 'Unapproved', unapprove_admin_comment_path(comment), :method =>:post %> </td>
   <% else %>
     <td> <%= link_to 'Approved', approve_admin_comment_path(comment), :method =>:postt%> </td>
  <% end %>
  </tr>
<% end %>
</table>
<%= will_paginate @comments %>
<br />

app/views/admin/comments/show.html.erb
  <b>Post:</b>
  <p>Title: <%= @post.title %></p>
  Body: <%= @post.body %>


<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>


<%= link_to 'Edit', edit_admin_comment_path(@comment) %> |
<%= link_to 'Back', admin_comments_path %> |
<%= link_to 'Destroy', [:admin, @comment], :method => :delete, :confirm => 'Are you sure to delete?' %>