config/routes.rb
Mypolice::Application.routes.draw do |map|
  resources :addresses

  resources :responses

  devise_for :polices

  devise_for :admins

  resources :posts do
    resources :responses
    resources :comments
  end
  
  resources :tags

  namespace :admin do 
    resources :posts do  
        post :approve, :on => :member
        post :unapprove, :on => :member
        get :approved, :on => :collection
        get :unapproved, :on => :collection
      end
    resources :comments do  
        post :approve, :on => :member
        post :unapprove, :on => :member
        get :approved, :on => :collection
        get :unapproved, :on => :collection
      end
    resources :polices do
        post :cheif, :on => :member
        post :uncheif, :on =>:member
    end
    resources :responses, :users, :tags, :categories, :whos
  end

  namespace :police do
    resources :polices
  end

  devise_for :users  
  
  match "/admin" => "admin/dashboard#index", :as => :admin_root
  match "/police" => "police/dashboard#index", :as => :police_root
   
  match '/police/profile/:id/' => 'police/polices#show', :as => :profile   

  match '/about'=>'about#index', :as =>:about_root
  match '/tools'=>'tools#index', :as =>:tools_root
  match 'police/help'=>"police/help#index", :as=>:police_help_root

  match '/tellusyourstory'=>'posts#new', :as=>:tellusyourstory

  root :to =>"home#index"
end

app/models/address.rb
class Address < ActiveRecord::Base
  has_many :post
=begin
  validates :address_line1, :presence=>true
  validates :city, :presence=>true
  validates :postcode, :presence=>true, :format=>{:with=>/^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$/}
  validates :country, :presence=>true
  before_validation :ensure_postcode_is_uppercase
  
  protected
  def ensure_postcode_is_uppercase
    self.postcode.upcase!
  end
=end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :registerable, :confirmable, :timeoutable and :activatable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :presence=>true, :length=>{:minimum=>1, :maximum=>50}
  has_many :post,:dependent=>:destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :presence=>true
  belongs_to :post
  belongs_to :user
  scope :approved, where(:approved => true)
  scope :unapproved, where(:approved => false)
end

app/models/police.rb
class Police < ActiveRecord::Base
  has_many :responses
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email,:name, :password, :password_confirmation
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :body, :presence=>true, :length=>{:minimum=>140}
  validates :title, :presence=>true
  has_many :comments, :dependent => :destroy
  has_many :responses, :dependent => :destroy
  belongs_to :user
  belongs_to :address
  has_one :storydata
  belongs_to :who
  belongs_to :category
  scope :approved, where(:approved=>true)
  scope :unapproved, where(:approved=>false)
  scope :anonymous, where(:use_id=>nil) 
  acts_as_taggable
  cattr_reader :per_page
  @@per_page =10

  def self.search(search, page)
    paginate :per_page => 10, :page => page,
             :conditions => ['body like ?', "%#{search}%"], :order => 'created_at DESC'
  end
 
  
end

app/models/response.rb
class Response < ActiveRecord::Base
  validates :body, :presence=>true
  belongs_to :post
  belongs_to :police
end

app/models/storydata.rb
class Storydata < ActiveRecord::Base
  belongs_to :post;
  belongs_to :who;
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable :confirmable and :activatable
  #acts_as_authentic 
  has_many :post, :dependent => :destroy
  has_many :comment, :dependent => :destroy
  #has_many :assignment
  #has_many :roles, :through => :assignment
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
  
end

app/models/who.rb
class Who < ActiveRecord::Base
  validates :name, :presence=>true
  has_many :storydata
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.approved.paginate :page=>1, :per_page=>'3', :order=>'created_at DESC'
    @users = User.paginate :page=>1, :per_page=>'10', :order=>'created_at DESC'
    @responses = Response.paginate :page=>1, :per_page=>'10', :order=>'created_at DESC'
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_role
    if current_user 
      return current_user
    elsif current_admin 
      return current_admin
    elsif current_police 
      return current_police
    end
  end

  def current_role_name
    return current_role.class.to_s.downcase if current_role
  end

  def mark_required(object, attribute)
    "*" if object.class.validators_on(attribute).map(&:class).include? ActiveModel::Validations::PresenceValidator
  end  

  def title(page_title)  
    content_for(:title) { page_title }  
  end  


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/storydata_helper.rb
module StorydataHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/shared/_error_message.html.haml
-if target.class <= Array
  -a_tartget = target
-else 
  -a_target =[target]
-target.each do |t|
  -if t.errors.any?
    #errorExplanation
      %h2
        = pluralize(t.errors.count, "error")
        prohibited this record from being saved:
      %ul
        -t.errors.full_messages.each do |msg| 
          %li 
            = msg

app/views/shared/_footer.haml
#footer
  .footerwrapper
    #footerlogo.footercolumn
      %a{:title=>"Mypolice", :href=>root_path}
        %img{:title=>"Mypolicelogo", :src=>image_path("logo.png"), :alt=>"mypolice logo"}
    %ul.footercolumn
      %li
        %a{:title=>"Blog", :href=>"#"} Blog    
      %li
        %a{:title=>"Team", :href=>"#"} Team
      %li
        %a{:title=>"Contact us", :href=>"#"} Contact us

    %ul.footercolumn
      %li
        %a{:title=>"Terms and Conditions", :href=>"#"} Terms and Conditions
      %li
        %a{:title=>"Privacy", :href=>"#"} Privacy
      %li
        %a{:title=>"Other stuff", :href=>"#"} Other stuff
      %li
        %a{:title=>"Here", :href=>"#"} Here

    .otherlink
      %ul 
        %li Mypolice are delighted to work with
        %li
          %a{:href=>"http://www.sicamp.org/", :title=>"social innovation camp"}
            %img{:src=>image_path("workwith/sic.png"), :title=>"social innovation camp", :alt=>"social innovation camp", :height=>"50px;"}
          %a{:href=>"http://www.4ip.org.uk/",:title=>"4ip",:target=>"_blank"}
            %img{:src=>image_path("workwith/4ip.png"),:title=>"4ip",:alt=>"4i"}
        %li
          %a{:href=>"http://www.socialentrepreneursfund.co.uk/", :title=>"social entrepreneurs fund",:target=>"_blank"}
            %img{:src=>image_path("workwith/sef.png"),:title=>"social entrepreneurs fund",:alt=>"social entrepreneurs fund"}

    .otherlink#last
      %ul
        %li We have been featured here:
        %li
          %a{:href=>"http://news.bbc.co.uk/1/hi/technology/8562308.stm", :title=>"BBC", :target=>"_blank"}
            %img{:src=>image_path("workwith/bbc.png"), :title=>"BBC", :alt=>"BBC"}
          %a{:href=>"http://news.sky.com/skynews/Home/UK-News/Nottinghamshire-Police-Ranked-Worse-In-UK-By-HMIC-Row-Over-MyPoliceOrg-Domain-Name/Article/201003215571295?f=rss", :title=>"Sky News", :target=>"_blank"}
            %img{:src=>image_path("workwith/skynews.png"), :title=>"Sky News", :alt=>"Sky News"}
          %a{:href=>"#", :title=>"WEST", :target=>"_blank"}
            %img{:src=>image_path("workwith/west.png"), :title=>"WEST", :alt=>"WEST"}
        %li
          %a{:href=>"http://www.guardian.co.uk/technology/blog/2010/mar/10/mypolice-government-row", :title=>"guardian", :target=>"_blank"}
            %img{:src=>image_path("workwith/guardian.png"), :title=>"guardian", :alt=>"guardian" }
          %a{:href=>"http://www.heraldscotland.com/news/home-news/web-designers-blast-police-for-internet-rip-off-1.1013001", :title=>"The Herald", :target=>"_blank"}
            %img{:src=>image_path("workwith/theherald.png"), :title=>"The Herald", :alt=>"The Herald"}
        %li
          %a{:href=>"#", :title=>"NESTA", :target=>"_blank"}
            %img{:src=>image_path("workwith/nesta.png"), :title=>"NESTA", :alt=>"NESTA"}
          %a{:href=>"#", :title=>"THE COURIER", :target=>"_blank"}
            %img{:src=>image_path("workwith/thecourier.png"), :title=>"THE COURIER", :alt=>"THE COURIER"}
      
  #copyright
    %p
      &copy; 2010 My conversation ltd (Mypolice)

app/views/shared/_head.html.haml
%head
  %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}
  %title= yield(:title) 
  = stylesheet_link_tag 'compiled/screen.css', :media =>'screen,projection'
  = stylesheet_link_tag 'compiled/print.css', :media=>'print'
  /[if lt IE 8]
  = stylesheet_link_tag 'compiled/ie.css', :mdeia=>'screen,projection'
  = stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/base/jquery-ui.css"
  = stylesheet_link_tag 'jquery.fancybox-1.3.1.css'
  = javascript_include_tag "jquery-1.4.2.min", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js"
  = javascript_include_tag "jquery.validate"
  = javascript_include_tag "jquery.history"
  = javascript_include_tag "jquery.rails"
  = javascript_include_tag "jquery.validate"
  = javascript_include_tag "jquery.form"
  = javascript_include_tag 'jquery.form.wizard-2.0.1-min'
  = javascript_include_tag 'jquery.fancybox-1.3.1.pack.js'
  = auto_discovery_link_tag :atom, posts_path(:format=>:atom)
  = csrf_meta_tag 

app/views/shared/_header.html.haml
#header
  #logo
    %a{:title=>"Mypolice", :href=>root_path}
      =image_tag("mypolice-logo.png")
  #menu
    .tabs
      = render_navigation
    %form{:action=>posts_path,:method=>'get',:id=>'searchbox'} 
      -if params[:search].nil?
        =text_field_tag :search ,"Search Stories", {:onclick=>"if(this.defaultValue==this.value) this.value=''"}
      -else
        =text_field_tag :search, params[:search], {:onclick=>"if(this.defaultValue==this.value) this.value=''"}
      =submit_tag "GO", :name=>nil, :id=>:submitbutton 

    %ul.hmenu 
      = render :partial =>"devise/menu/login_items"
      = render :partial => "devise/menu/registration_items"
    
    

app/views/shared/_policefooter.haml
#footer
  #footerlogo
    %a{:title=>"Mypolice", :href=>"#"}
      %img{:title=>"Mypolicelogi", :src=>"/images/policelogo.png",:width=>"100px"}
  %ul#relatedlink
    %li
      %a{:title=>"Blog", :href=>"#"} Blog    
    %li
      %a{:title=>"Team", :href=>"#"} Team
    %li
      %a{:title=>"Contact us", :href=>"#"} Contact us

  %ul#legallink
    %li
      %a{:title=>"Terms and Conditions", :href=>"#"} Terms and Conditions
    %li
      %a{:title=>"Privacy", :href=>"#"} Privacy
    %li
      %a{:title=>"Other stuff", :href=>"#"} Other stuff
    %li
      %a{:title=>"Here", :href=>"#"} Here
  #copyright
    %p
      &copy; MyPolice 2010

app/views/shared/_policehead.html.haml
%head
  %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}
  %title= yield(:title) 
  = stylesheet_link_tag 'compiled/police.css', :media =>'screen,projection'
  = stylesheet_link_tag 'compiled/print.css', :media=>'print'
  /[if lt IE 8]
    =stylesheet_link_tag 'compiled/ie.css', :mdeia=>'screen,projection'
  = stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css"
  = javascript_include_tag "jquery-1.4.2.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application"
  = javascript_include_tag "jquery.validate"
  = javascript_include_tag 'jquery.rails'
  = auto_discovery_link_tag :atom, posts_path(:format= >:atom)
  = csrf_meta_tag 

app/views/shared/_policeheader.html.haml
#header
  #logo
    %a{:title=>"Mypolice", :href=>root_path}
      %img{:title=>"Mypolicelogi", :src=>"/images/policelogo.png"}
  #menu
    %form{:action=>posts_path,:method=>'get',:id=>'searchbox'} 
      %p
        -if params[:search].nil?
          = text_field_tag :search ,"Search Stories", {:onclick=>"if(this.defaultValue==this.value) this.value=''"}
        -else
          =text_field_tag :search, params[:search], {:onclick=>"if(this.defaultValue==this.value) this.value=''"}
        =submit_tag "GO", :name=>nil, :id=>:submitbutton 
    %ul.hmenu 
      = render :partial =>"devise/menu/login_items"
      = render :partial => "devise/menu/registration_items"
    .tabs
      =render_navigation
    -#begin
      %ul
        %li
          =link_to "Police Dashboard", police_root_path, :class=>"selected"
        %li
          =link_to "Help"